In [29]:
import pandas as pd

In [30]:
inspections = pd.read_csv("project1Data/currentOpenInspections.csv")

In [31]:
inspections

,Borough,RestaurantName,SeatingChoice,LegalBusinessName,BusinessAddress,RestaurantInspectionID,IsSidewayCompliant,IsRoadwayCompliant,SkippedReason,InspectedOn,AgencyCode,Postcode,Latitude,Longitude,CommunityBoard,CouncilDistrict,CensusTract,BIN,BBL,NTA
0,Manhattan,Oscar Wilde,both,Camelot Castle LLC,45 West 27th st,72891,NaN,Non-Compliant,NaN,12/20/2021 04:06:58 PM,DOT,10001,40.744876,-73.989657,5.0,3.0,58.0,1015677.0,1.008290e+09,Hudson Yards-Chelsea-Flatiron-Union Square
1,Manhattan,LA RUBIA RESTAURANT,both,LA RUBIA RESTAURANT INC,3517 BROADWAY,72892,NaN,For HIQA Review,NaN,12/20/2021 04:18:42 PM,DOT,10031,40.825863,-73.950874,9.0,7.0,229.0,1062369.0,1.020910e+09,Hamilton Heights
2,Manhattan,Thai Sliders,sidewalk,Silom Thai Inc,150 8th Ave,72893,NaN,Non-Compliant,NaN,12/20/2021 04:35:41 PM,DOT,10011,40.741906,-74.000945,4.0,3.0,81.0,1013845.0,1.007670e+09,Hudson Yards-Chelsea-Flatiron-Union Square
3,Brooklyn,Otway,both,St james 930 LLC,930 Fulton street,72894,NaN,Cease and Desist,NaN,12/20/2021 04:38:45 PM,DOT,11238,40.682833,-73.963833,2.0,35.0,201.0,3335112.0,3.020130e+09,Clinton Hill
4,Brooklyn,WILLIAMSBURG THAI CUISINE,both,WILLIAMSBURG THAI CUISINE NY INC,212 BEDFORD AVENUE,72896,NaN,Compliant,NaN,12/20/2021 04:52:41 PM,DOT,11249,40.716913,-73.958728,1.0,33.0,553.0,3062192.0,3.023350e+09,North Side-South Side
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79198,Brooklyn,Sunshine Co,both,780 Washington LLC,780 Wahington Ave,107873,NaN,Pre-Removal,NaN,12/01/2023 03:44:49 PM,DOT,11238,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79199,Manhattan,MOUSTACHE,sidewalk,BEDFORD PITZA CORP,29 7 AVENUE SOUTH,107874,NaN,Cease and Desist,NaN,12/01/2023 04:13:28 PM,DOT,10014,40.730812,-74.004395,2.0,3.0,67.0,1087324.0,1.005860e+09,West Village
79200,Brooklyn,Mekelburg's,both,"Hop, Stock & Barrel II LLC",319 Kent Avenue,107875,NaN,Skipped Inspection,No Seating,12/01/2023 04:42:51 PM,DOT,11238,40.713757,-73.967200,1.0,33.0,551.0,3424711.0,3.024280e+09,North Side-South Side
79201,Brooklyn,Sunday In Brooklyn,both,Sunday in Brooklyn LLC,348 Wythe Ave,107876,NaN,Compliant,NaN,12/01/2023 04:48:20 PM,DOT,11249,40.714171,-73.965208,1.0,33.0,551.0,3321284.0,3.024150e+09,North Side-South Side
79202,Brooklyn,Otway,both,St james 930 LLC,930 Fulton street,107877,NaN,For HIQA Review,NaN,12/01/2023 05:00:48 PM,DOT,11238,40.682833,-73.963833,2.0,35.0,201.0,3335112.0,3.020130e+09,Clinton Hill

In [32]:
applications = pd.read_csv("project1Data/Open_Restaurant_Applications__Historic__20231202.csv")

In [33]:
applications

,objectid,globalid,Seating Interest (Sidewalk/Roadway/Both),Restaurant Name,Legal Business Name,Doing Business As (DBA),Building Number,Street,Borough,Postcode,...,healthCompliance_terms,Time of Submission,Latitude,Longitude,Community Board,Council District,Census Tract,BIN,BBL,NTA
0,13610,{FD87ABAA-860E-4762-845D-8F0403D0246B},roadway,MADAME BONTE,BEANHOUSE LLC,MADAME BONTE,NaN,318 EAST 84 STREET,Manhattan,10028,...,yes,06/09/2022 04:26:00 PM,40.776277,-73.952051,8.0,5.0,138.0,1049941.0,1.015460e+09,Yorkville
1,5900,{3B07E4C0-07B7-4079-8333-64446CC3EE03},sidewalk,Seasoned Vegan,"Seasoned Vegan, LLC","Seasoned Vegan, LLC",55,St. Nicholas Avenue,Manhattan,10026,...,yes,06/26/2020 08:38:00 PM,40.800500,-73.952507,10.0,9.0,216.0,1054995.0,1.018220e+09,Central Harlem South
2,13018,{137C575D-DC14-4F9D-83D9-A3FFE513B3B8},sidewalk,AMERICAS CAFE &amp; GRILL,68TH GRILL INC,AMERICAS CAFE &amp; GRILL,NaN,1159 3 AVENUE,Manhattan,10065,...,yes,10/22/2021 11:01:00 AM,40.766845,-73.962708,8.0,4.0,118.0,1043896.0,1.014220e+09,Lenox Hill-Roosevelt Island
3,11630,{15270732-2A78-4C24-89DD-BE8DD916F115},roadway,SUSHI SEKI,SEKI INC,SUSHI SEKI,undefined,208 WEST 23 STREET,Manhattan,10011,...,yes,12/14/2020 07:54:00 PM,40.744338,-73.996240,4.0,3.0,91.0,1014129.0,1.007720e+09,Hudson Yards-Chelsea-Flatiron-Union Square
4,13137,{EF9C8173-91D1-496E-8BD4-B02BEADC2A21},roadway,Sami &amp; Susu,AMIR NATHAN,Sami & Susu,NaN,190 ORCHARD STREET,Manhattan,10002,...,yes,12/22/2021 12:46:00 PM,40.722124,-73.988160,3.0,1.0,3001.0,1005393.0,1.004120e+09,Chinatown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14423,9799,{108C6784-54DB-480B-8627-CF0495D27A0E},both,KING OF SPADES INC.,KING OF SPADES INC.,KING OF SPADES INC.,1425,COLLEGE POINT BLVD,Queens,11356,...,yes,08/04/2020 03:27:00 PM,40.784739,-73.845776,7.0,19.0,929.0,4098349.0,4.040850e+09,College Point
14424,8215,{7B8EC275-D470-4106-819E-03FC0E1F9717},both,LA QUEEN TEA HOUSE INC,LA QUEEN TEA HOUSE INC,LA QUEEN TEA HOUSE INC,752B,61ST ST,Brooklyn,11220,...,yes,07/13/2020 03:53:00 PM,40.635543,-74.011220,7.0,38.0,118.0,3143885.0,3.057940e+09,Sunset Park East
14425,2895,{476f88d2-d3e8-4e83-8686-8bac2f752cf5},sidewalk,aahar indina cuisine,vidhan bhatt inc.,vidhan bhatt inc.,10,murray street,Manhattan,10007,...,yes,06/21/2020 01:46:00 PM,40.713298,-74.007773,1.0,1.0,21.0,1001399.0,1.001240e+09,SoHo-TriBeCa-Civic Center-Little Italy
14426,607,ff0d04ef-1d9a-47d6-8f20-8bdbdbce2792,sidewalk,le cafe coffee,le cafe coffee llc,le cafe coffee llc,145,fourth av,Manhattan,10003,...,yes,06/19/2020 01:19:00 PM,40.733916,-73.989872,3.0,2.0,42.0,1077569.0,1.005590e+09,East Village
14427,6641,{9DBBF87C-AE3D-4487-81A4-30E44806614F},both,KASHKAVAL GARDEN,KASHKAVAL Kitchen LLC,KASHKAVAL Kitchen LLC,852,9th Avenue,Manhattan,10019,...,yes,06/30/2020 10:33:00 PM,40.766927,-73.986423,4.0,3.0,139.0,1025423.0,1.010460e+09,Clinton

In [34]:
inspection_results = pd.read_csv("project1Data/DOHMH_New_York_City_Restaurant_Inspection_Results_20231202.csv")

In [35]:
inspection_results

,CAMIS,DBA,BORO,BUILDING,STREET,ZIPCODE,PHONE,CUISINE DESCRIPTION,INSPECTION DATE,ACTION,...,INSPECTION TYPE,Latitude,Longitude,Community Board,Council District,Census Tract,BIN,BBL,NTA,Location Point1
0,50106271,SOUR MOUSE,Manhattan,110,DELANCEY STREET,10002.0,6462567220,NaN,01/01/1900,NaN,...,NaN,40.718640,-73.988481,103.0,1.0,1800.0,1087565.0,1.004100e+09,MN27,NaN
1,50117820,MODELLO BAR - BARCLAYS CENTER,Brooklyn,620,ATLANTIC AVENUE,11217.0,9174174384,NaN,01/01/1900,NaN,...,NaN,40.683447,-73.975691,302.0,35.0,12902.0,3398156.0,3.011180e+09,BK37,NaN
2,50141790,NaN,Manhattan,30,EAST 20 STREET,10003.0,9176670036,NaN,01/01/1900,NaN,...,NaN,40.738929,-73.989221,105.0,2.0,5200.0,1016181.0,1.008480e+09,MN13,NaN
3,50134862,FINE AND RAW CHOCOLATE,Brooklyn,70,SCOTT AVENUE,11237.0,6462440734,NaN,01/01/1900,NaN,...,NaN,40.709853,-73.922706,301.0,34.0,44900.0,3070597.0,3.029900e+09,BK90,NaN
4,50127238,THE DELUXE PARTY KTV,Queens,3420,LINDEN PL,11354.0,9172957843,NaN,01/01/1900,NaN,...,NaN,40.766275,-73.831338,407.0,20.0,86900.0,4112007.0,4.049500e+09,QN22,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209784,50129459,BLUEBERRY,Brooklyn,1849,CONEY ISLAND AVENUE,11230.0,3473719836,Bakery Products/Desserts,08/03/2023,Violations were cited in the following area(s).,...,Cycle Inspection / Initial Inspection,40.611980,-73.962744,314.0,48.0,54200.0,3181708.0,3.067580e+09,BK43,NaN
209785,41444866,PIES-N-THIGHS,Brooklyn,166,SOUTH 4 STREET,11211.0,3475296090,American,08/09/2023,Violations were cited in the following area(s).,...,Cycle Inspection / Re-inspection,40.711289,-73.961300,301.0,34.0,52300.0,3063458.0,3.024460e+09,BK73,NaN
209786,50123805,QK Restaurant Inc.,Queens,4626,KISSENA BLVD,11355.0,7189990806,Chinese,08/01/2022,Violations were cited in the following area(s).,...,Pre-permit (Operational) / Re-inspection,40.750040,-73.818520,407.0,20.0,84500.0,4314742.0,4.051490e+09,QN22,NaN
209787,50056510,GINBO'S HAMBURGER HOUSE,Bronx,118,EAST 170 STREET,10452.0,3479634644,Hamburgers,09/28/2022,Violations were cited in the following area(s).,...,Cycle Inspection / Compliance Inspection,40.839304,-73.915334,204.0,16.0,22102.0,2008084.0,2.028420e+09,BX63,NaN
209788,41112524,ADRIENNE'S PIZZA BAR,Manhattan,54,STONE STREET,10004.0,2122483838,Italian,03/10/2022,Violations were cited in the following area(s).,...,Cycle Inspection / Initial Inspection,40.704403,-74.010211,101.0,1.0,900.0,1088620.0,1.000298e+09,MN25,NaN

### Let's start off with inspections dataset and do some EDA on it to find out what the data looks like and it's inconsistencies

In [36]:
inspections.info()
no_rows = len(inspections)
print(f"Inspections df has {no_rows} rows")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79203 entries, 0 to 79202
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Borough                 79203 non-null  object
 1   RestaurantName          79195 non-null  object
 2   SeatingChoice           79203 non-null  object
 3   LegalBusinessName       79202 non-null  object
 4   BusinessAddress         79203 non-null  object
 5   RestaurantInspectionID  79203 non-null  int64
 6   IsSidewayCompliant      0 non-null      float64
 7   IsRoadwayCompliant      79203 non-null  object
 8   SkippedReason           19866 non-null  object
 9   InspectedOn             79203 non-null  object
 10  AgencyCode              67240 non-null  object
 11  Postcode                79203 non-null  int64
 12  Latitude                71320 non-null  float64
 13  Longitude               71320 non-null  float64
 14  CommunityBoard          71320 non-null  float64
 15  CouncilDistrict         71320 non-null  float64
 16  CensusTract             71320 non-null  float64
 17  BIN                     70899 non-null  float64
 18  BBL                     70899 non-null  float64
 19  NTA                     71320 non-null  object
dtypes: float64(8), int64(2), object(10)
memory usage: 12.1+ MB
Inspections df has 79203 rows

In [37]:
def missing_columns(df):
    total = 0
    for column in df.columns:
        missing = df[column].isnull().sum()
        total += missing
        if missing != 0:
            print(f"{column} --> {df[column].isnull().sum()}")
    if total == 0:
        print("No missing values")

missing_columns(inspections)

RestaurantName --> 8
LegalBusinessName --> 1
IsSidewayCompliant --> 79203
SkippedReason --> 59337
AgencyCode --> 11963
Latitude --> 7883
Longitude --> 7883
CommunityBoard --> 7883
CouncilDistrict --> 7883
CensusTract --> 7883
BIN --> 8304
BBL --> 8304
NTA --> 7883

In [38]:
null_ll_rows = inspections.query('Latitude != Latitude')
null_ll_rows.head()

,Borough,RestaurantName,SeatingChoice,LegalBusinessName,BusinessAddress,RestaurantInspectionID,IsSidewayCompliant,IsRoadwayCompliant,SkippedReason,InspectedOn,AgencyCode,Postcode,Latitude,Longitude,CommunityBoard,CouncilDistrict,CensusTract,BIN,BBL,NTA
16,Manhattan,Reliable Food,sidewalk,"Reliable Food, Inc",59 54th st,72908,NaN,Compliant,NaN,12/21/2021 10:26:26 AM,DOT,10022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Manhattan,SeanGCOs Bar & Kitchen,both,Carramore Restaurant Inc,38-42W 48th st,72920,NaN,Non-Compliant,NaN,12/21/2021 11:14:10 AM,DOT,10036,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Manhattan,JUE LAN CLUB,both,Jade Farm LLC,49W 20th Street,10003,NaN,Compliant,NaN,07/14/2020 04:44:34 PM,DEP,10011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Manhattan,Pazza Notte,both,Pasta la Vista inc.,1375 Avenue of teh Americas,72923,NaN,Under Review,NaN,12/21/2021 11:21:37 AM,DOT,10019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,Manhattan,The Mean Fiddler,both,Castleknock Inc,266 W 47th,72944,NaN,Compliant,NaN,12/21/2021 12:25:15 PM,DOT,10036,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### As we can see where there are null values in Latitude and Longitude the same applies to few other columns so lets remove those rows and drop the column isSidewaycompliant, because its all null

In [39]:
inspections.dropna(subset=['BBL'], inplace = True)
inspections.drop(columns=['IsSidewayCompliant'], inplace = True)

In [40]:
missing_columns(inspections)

RestaurantName --> 8
LegalBusinessName --> 1
SkippedReason --> 53185
AgencyCode --> 10620

In [41]:
inspections.query('RestaurantName != RestaurantName')

,Borough,RestaurantName,SeatingChoice,LegalBusinessName,BusinessAddress,RestaurantInspectionID,IsRoadwayCompliant,SkippedReason,InspectedOn,AgencyCode,Postcode,Latitude,Longitude,CommunityBoard,CouncilDistrict,CensusTract,BIN,BBL,NTA
10308,Brooklyn,NaN,both,EL SANCHOS RESTAURANT CORP.,7410 3 AVENUE,86227,Skipped Inspection,No Seating,07/27/2022 05:55:54 PM,DOT,11209,40.632005,-74.027579,10.0,43.0,66.0,3148230.0,3.059280e+09,Bay Ridge
10309,Brooklyn,NaN,both,EL SANCHOS RESTAURANT CORP.,7410 3 AVENUE,86228,Pre-Suspension,NaN,07/27/2022 05:55:54 PM,DOT,11209,40.632005,-74.027579,10.0,43.0,66.0,3148230.0,3.059280e+09,Bay Ridge
10690,Brooklyn,NaN,both,EL SANCHOS RESTAURANT CORP.,7410 3 AVENUE,86639,Suspended and Deactivated,NaN,08/03/2022 11:59:36 PM,NaN,11209,40.632005,-74.027579,10.0,43.0,66.0,3148230.0,3.059280e+09,Bay Ridge
49580,Brooklyn,NaN,both,EL SANCHOS RESTAURANT CORP.,7410 3 AVENUE,50907,Non-Compliant,NaN,05/14/2021 02:05:25 PM,DOT,11209,40.632005,-74.027579,10.0,43.0,66.0,3148230.0,3.059280e+09,Bay Ridge
53812,Brooklyn,NaN,both,EL SANCHOS RESTAURANT CORP.,7410 3 AVENUE,57441,Cease and Desist,NaN,06/28/2021 01:09:48 PM,DOT,11209,40.632005,-74.027579,10.0,43.0,66.0,3148230.0,3.059280e+09,Bay Ridge
60080,Brooklyn,NaN,both,EL SANCHOS RESTAURANT CORP.,7410 3 AVENUE,65699,Cease and Desist,NaN,09/02/2021 11:35:58 AM,DOT,11209,40.632005,-74.027579,10.0,43.0,66.0,3148230.0,3.059280e+09,Bay Ridge
64799,Brooklyn,NaN,both,EL SANCHOS RESTAURANT CORP.,7410 3 AVENUE,71810,For HIQA Review,NaN,12/05/2021 04:50:22 PM,DOT,11209,40.632005,-74.027579,10.0,43.0,66.0,3148230.0,3.059280e+09,Bay Ridge
65145,Brooklyn,NaN,both,EL SANCHOS RESTAURANT CORP.,7410 3 AVENUE,72163,Skipped Inspection,No Seating,12/09/2021 04:57:55 PM,DOT,11209,40.632005,-74.027579,10.0,43.0,66.0,3148230.0,3.059280e+09,Bay Ridge

In [42]:
inspections[inspections['LegalBusinessName'] == 'EL SANCHOS RESTAURANT CORP.']

,Borough,RestaurantName,SeatingChoice,LegalBusinessName,BusinessAddress,RestaurantInspectionID,IsRoadwayCompliant,SkippedReason,InspectedOn,AgencyCode,Postcode,Latitude,Longitude,CommunityBoard,CouncilDistrict,CensusTract,BIN,BBL,NTA
10308,Brooklyn,NaN,both,EL SANCHOS RESTAURANT CORP.,7410 3 AVENUE,86227,Skipped Inspection,No Seating,07/27/2022 05:55:54 PM,DOT,11209,40.632005,-74.027579,10.0,43.0,66.0,3148230.0,3.059280e+09,Bay Ridge
10309,Brooklyn,NaN,both,EL SANCHOS RESTAURANT CORP.,7410 3 AVENUE,86228,Pre-Suspension,NaN,07/27/2022 05:55:54 PM,DOT,11209,40.632005,-74.027579,10.0,43.0,66.0,3148230.0,3.059280e+09,Bay Ridge
10690,Brooklyn,NaN,both,EL SANCHOS RESTAURANT CORP.,7410 3 AVENUE,86639,Suspended and Deactivated,NaN,08/03/2022 11:59:36 PM,NaN,11209,40.632005,-74.027579,10.0,43.0,66.0,3148230.0,3.059280e+09,Bay Ridge
49580,Brooklyn,NaN,both,EL SANCHOS RESTAURANT CORP.,7410 3 AVENUE,50907,Non-Compliant,NaN,05/14/2021 02:05:25 PM,DOT,11209,40.632005,-74.027579,10.0,43.0,66.0,3148230.0,3.059280e+09,Bay Ridge
53812,Brooklyn,NaN,both,EL SANCHOS RESTAURANT CORP.,7410 3 AVENUE,57441,Cease and Desist,NaN,06/28/2021 01:09:48 PM,DOT,11209,40.632005,-74.027579,10.0,43.0,66.0,3148230.0,3.059280e+09,Bay Ridge
60080,Brooklyn,NaN,both,EL SANCHOS RESTAURANT CORP.,7410 3 AVENUE,65699,Cease and Desist,NaN,09/02/2021 11:35:58 AM,DOT,11209,40.632005,-74.027579,10.0,43.0,66.0,3148230.0,3.059280e+09,Bay Ridge
64799,Brooklyn,NaN,both,EL SANCHOS RESTAURANT CORP.,7410 3 AVENUE,71810,For HIQA Review,NaN,12/05/2021 04:50:22 PM,DOT,11209,40.632005,-74.027579,10.0,43.0,66.0,3148230.0,3.059280e+09,Bay Ridge
65145,Brooklyn,NaN,both,EL SANCHOS RESTAURANT CORP.,7410 3 AVENUE,72163,Skipped Inspection,No Seating,12/09/2021 04:57:55 PM,DOT,11209,40.632005,-74.027579,10.0,43.0,66.0,3148230.0,3.059280e+09,Bay Ridge

In [43]:
#Based on other rows we can fill the restaurant name with the prefix of legalbusinessname without the last part of CORP.
inspections["RestaurantName"].fillna('EL SANCHOS RESTAURANT',inplace = True)

In [44]:
missing_columns(inspections)

LegalBusinessName --> 1
SkippedReason --> 53185
AgencyCode --> 10620

In [45]:
inspections.query('LegalBusinessName != LegalBusinessName')

,Borough,RestaurantName,SeatingChoice,LegalBusinessName,BusinessAddress,RestaurantInspectionID,IsRoadwayCompliant,SkippedReason,InspectedOn,AgencyCode,Postcode,Latitude,Longitude,CommunityBoard,CouncilDistrict,CensusTract,BIN,BBL,NTA
61320,Bronx,Pancho Villa Restaurant Inc,sidewalk,NaN,2274 Jerome Av,67683,Skipped Inspection,No Seating,09/17/2021 02:29:24 PM,DOT,10453,40.858512,-73.903804,5.0,14.0,239.0,2014064.0,2.031860e+09,Fordham South

In [46]:
inspections["LegalBusinessName"].fillna('Pancho Villa Restaurant Inc',inplace = True)

In [47]:
inspections.query('LegalBusinessName != LegalBusinessName')

Empty DataFrame
Columns: [Borough, RestaurantName, SeatingChoice, LegalBusinessName, BusinessAddress, RestaurantInspectionID, IsRoadwayCompliant, SkippedReason, InspectedOn, AgencyCode, Postcode, Latitude, Longitude, CommunityBoard, CouncilDistrict, CensusTract, BIN, BBL, NTA]
Index: []

In [48]:

missing_columns(inspections)

SkippedReason --> 53185
AgencyCode --> 10620

#### So with skipped reason it is impossible to fill the missing values, so what we can do is fill the missing values with something like "Not skipped", but first we have to check if everything matches with Skipped inspection in IsRoadwayCompliant

In [49]:
(inspections['IsRoadwayCompliant'] != 'Skipped Inspection').sum()

53185

In [50]:
inspections["SkippedReason"].fillna('Not skipped',inplace = True)

In [74]:
inspections.duplicated(subset=['RestaurantName','InspectedOn']).sum()

2197

In [77]:
inspections.drop_duplicates(subset=['RestaurantName','InspectedOn'], inplace=True)

In [78]:
inspections.duplicated(subset=['RestaurantName','InspectedOn']).sum()

0

#### As of now I dont have an idea how to fill the agencycode column so lets leave some nulls and see if the column will be even needed further into analysis
#### Lets now get into cleaning next dataset

In [58]:
applications.sample(5)

,objectid,globalid,Seating Interest (Sidewalk/Roadway/Both),Restaurant Name,Legal Business Name,Doing Business As (DBA),Building Number,Street,Borough,Postcode,...,healthCompliance_terms,Time of Submission,Latitude,Longitude,Community Board,Council District,Census Tract,BIN,BBL,NTA
1897,10014,{41F74F8B-0C67-4093-826F-EC5E3AB3DBBF},openstreets,ABC El Salvadorin Grocery INC,ABC El Salvadorin Grocery Inc,ABC El Salvadorin Grocery Inc,4620,5th,Brooklyn,11220,...,yes,08/07/2020 02:51:00 PM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7396,7304,{4DA440B2-3023-453F-8242-8FDA13DCC314},both,Citrico,Luneta LLC,Citrico,681,Washington Avenue,Brooklyn,11216,...,yes,07/05/2020 12:57:00 PM,40.676894,-73.963584,8.0,35.0,205.0,3325277.0,3.011540e+09,Prospect Heights
2889,8874,{B563EAD6-3138-46CA-8092-ABA952E1AE66},both,MICHELADA HOUSE REST,MICHELADA HOUSE NY II INC,MICHELADA HOUSE REST,88-19,ROOSEVELT AVE,Queens,11372,...,yes,07/18/2020 06:18:00 PM,40.748259,-73.878086,3.0,21.0,277.0,4444853.0,4.014760e+09,Jackson Heights
13973,3033,{54f3e560-6c4b-430d-84a6-305bb0383ba3},both,Ricky's Cafe,Menashe Restaurant Corp.,Ricky's Cafe,75-02,37th ave.,Queens,11372,...,yes,06/21/2020 05:01:00 PM,40.749070,-73.890666,3.0,25.0,287.0,4029851.0,4.012860e+09,Jackson Heights
375,12290,{FEBED7B4-C2DD-44F9-80B2-499921084C26},both,EMPIRE DINER,210 EMPIRE LLC,EMPIRE DINER,undefined,210 10 AVENUE,Manhattan,10011,...,yes,04/21/2021 03:33:00 PM,40.747294,-74.004443,4.0,3.0,93.0,1080370.0,1.007200e+09,Hudson Yards-Chelsea-Flatiron-Union Square